Ellipse
AndeTaar/GASLanguageProcessor pull request #18
Opened 2024-05-06 14:13 UTC by ChristofferGamel

![image](https://github.com/AndeTaar/GASLanguageProcessor/assets/113096859/a3c5a69b-a377-4e2e-aec0-8bba9777f8d9)

2024-05-06 14:19 UTC, Thekid2002 requested changes

2024-05-06 14:19 UTC, Thekid2002 commented on GASLanguageProcessor/AST/Expressions/Terms/Ellipse.cs
> +    public Expression? BorderColor { get; protected set; }
Colour

2024-05-06 14:19 UTC, Thekid2002 commented on GASLanguageProcessor/AST/Expressions/Terms/Ellipse.cs
> +        BorderColor = borderColor;
same

2024-05-06 14:19 UTC, Thekid2002 commented on GASLanguageProcessor/TableType/Scope.cs
> +                new Identifier("borderColor"),
colour

2024-05-06 14:19 UTC, Thekid2002 commented on GASLanguageProcessor/TableType/Scope.cs
> +                new Variable("borderColor", GasType.Colour),
colour

2024-05-06 14:19 UTC, Thekid2002 commented on GASLanguageProcessor/output/output.svg
Ik fuck med musen 🗡️

2024-05-06 14:19 UTC, Thekid2002 commented on GASLanguageProcessor/bin/Debug/net8.0/Frontend/test.gas
> +   return Ellipse(Center, Width, Width + 20, Fill, StrokeColour, Stroke);
Lav det tilbage til hvad det var før
og så tilføj en ellipse et andet sted

2024-05-06 14:45 UTC, ChristofferGamel commented
![image](https://github.com/AndeTaar/GASLanguageProcessor/assets/113096859/6c77d38d-70d3-4462-9709-ea186da1de52)

2024-05-07 08:08 UTC, Thekid2002 approved these changes

2024-05-07 08:08 UTC, merged